services:
  - type: web
    name: sob-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install --upgrade pip && pip install .
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: your_telegram_token
      - key: OPENAI_API_KEY
        value: your_openai_api_key
    healthCheckPath: /
